version: "3"

volumes:
  redis_data:
  sql_data:
  rabbit_data:
  blob_data:

services: 
    nginx:
        container_name: gateway
        build: 
            context: ./Nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
            - 443:443
        restart: always
    client:
        container_name: angular
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports: 
            - 5000:80
    webapi:
        container_name: webapi
        build: 
            context: ./API
            dockerfile: Dockerfile
        ports: 
            - 3000:80
        environment:
            redisConnection: "redis:6379"
            sqlConnection: "Server=sqlserver;Database=master;User=sa;Password=Pass123@;"
    azfunc:
        container_name: azfunc
        build: 
            context: ./AzFunction
            dockerfile: Dockerfile
        ports: 
            - 5050:80
        environment:
            AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;"
            RabbitMQConnection: "amqp://adminuser:adminpass@rabbitmq:5672"
            rabbitHost: "rabbitmq"
            rabbitUser: "adminuser"
            rabbitPass: "adminpass"
        depends_on:
            - rabbitmq
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        container_name: azurite
        command: "azurite --queueHost 0.0.0.0 --blobHost 0.0.0.0 --tableHost 0.0.0.0 -l /data"
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
        volumes:
            - blob_data:/data
    redis:
        container_name: redis
        image: "redis:latest"
        ports:
            - "6379:6379"
        expose:
            - "6379"
        volumes:
            - redis_data:/data
    redisinsight:
        container_name: redisinsight
        image: "redislabs/redisinsight:latest"
        ports:
            - "8001:8001"
        expose:
            - "8001"
        volumes:
            - redis_data:/data
    sqlserver:
        container_name: sqlserver
        image: "mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04"
        # volumes:
        #     - sql_data:/var/opt/mssql/data
        #     - sql_data:/var/opt/mssql/log
        #     - ./sql_data:/var/opt/mssql/data
        #     - ./sql_data:/var/opt/mssql/log
        environment:
            SA_PASSWORD: "Pass123@"
            ACCEPT_EULA: "Y"
    rabbitmq:
        container_name: rabbitmq
        build: 
            context: ./Rabbit
            dockerfile: Dockerfile
        ports:
            - "15672:15672"  
            - "5672:5672"        
        expose:
            - "15672"
            - "5672"
        volumes:
            - rabbit_data:/var/lib/rabbitmq
    